#!/bin/sh
# Copy this file to '/data/nv-local'

case "$1" in
        start)
                printf "Starting PumpLOG: "
                start-stop-daemon -S -b -x /data/pumpmon
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        stop)
                [ $? = 0 ] && echo "OK" || echo "FAIL"
                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;

        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac

exit 0
